import type { InstructorCourse } from "@/app/dashboard/instructor/InstructorClient";

export const mockCourses: InstructorCourse[] = [
  {
    id: "1",
    title: "Introduction to Python",
    description: "Learn Python from scratch with hands-on projects.",
    instructor: { _id: "t1", name: "Ada Lovelace", email: "ada@cognify.com" },
    thumbnail: { url: "", public_id: "" },
    status: "published",
    category: "Technology",
    createdAt: new Date(),
    updatedAt: new Date(),
    totalStudents: 84,
  },
  {
    id: "2",
    title: "Business Communication",
    description: "Master professional communication skills.",
    instructor: { _id: "t1", name: "Ada Lovelace", email: "ada@cognify.com" },
    thumbnail: { url: "", public_id: "" },
    status: "published",
    category: "Business",
    createdAt: new Date(),
    updatedAt: new Date(),
    totalStudents: 52,
  },
  {
    id: "3",
    title: "Advanced Design Systems",
    description: "Build scalable design systems from the ground up.",
    instructor: { _id: "t1", name: "Ada Lovelace", email: "ada@cognify.com" },
    thumbnail: { url: "", public_id: "" },
    status: "draft",
    category: "Design",
    createdAt: new Date(),
    updatedAt: new Date(),
    totalStudents: 0,
  },
];
